config/routes.rb
Its30::Application.routes.draw do
  
  get "userslist/show"
  get "users/show"
  get "user/show"
  get "search/result"
  mount RedactorRails::Engine => '/redactor_rails'
  get "index/home"
  resources :posts
  
  get "/list/:id", to: 'userslist#show', as: :userlist_show

  resources :asks do
    resources :comments
  end

  resources :meetups

  resources :news
  
  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "errors/access_denied"
  get 'access_denied' => 'errors#access_denied', as: :access_denied
  

  root 'index#home'

end

app/views/index/partial/_content.html.haml
.content
  .row
    =render 'index/partial/contentright'
    =render 'partial/sidebar/left/sidebar'
    

app/views/index/partial/_contentright.html.haml
.large-8.medium-8.large-push-4.medium-push-4.small-12.columns
  .content-right
    .content-right_news.padding-lr-15
      =render 'index/partial/postsblock'

app/views/index/partial/_latestnews.html.haml
.latest-news.full-width
  .row
    .large-12.medium-12.small-12.columns.padding-lr-10
      .large-7.medium-7.small-12.columns
        .latest-news_header-block
          %h1=@news_last.title
          =link_to 'Детальніше', @news_last, :class => "more-button_white"
      .large-4.medium-5.large-offset-1.small-12.columns
        .latest-news_another-news-block
          %h5.padding-lr-5 Інші новини
          - @news.each do |n|
            .latest-news_another-news-block_inner.padding-5
              =link_to n do
                %p.latest-news_another-news-block_time= n.created_at.to_s(:time)
                %a.latest-news_another-news-block_text=n.title

app/views/index/partial/_postsblock.html.haml
- @posts.each do |b|
  .content-right_news_inner
    .large-12.medium-12.small-12.columns
      .large-3.medium-3.small-4.columns
        .content-right_news_inner_post-img
          =link_to b do
            =image_tag b.imagep_url() if b.imagep?
      .large-9.medium-9.small-8.columns
        .content-right_news_inner_post-header
          %h5=b.title
      .large-9.medium-9.small-8.columns.content-right_news_inner_post-text-button_blue-author-time-fix
        .content-right_news_inner_post-text
          .cut
            %p=simple_format(b.content)
        .clear-both
        .content-right_news_inner_post-author-time
          %p=b.created_at.to_s(:db)
        =link_to 'Детальніше', b, :class => "more-button_blue"
.clear-both
= paginate @posts
-if user_signed_in?
  -if current_user.has_role?(:admin)
    =link_to 'Додати публікацію', new_post_path, :class => "more-button_blue"