config/routes.rb
Its30::Application.routes.draw do
  
  get "userslist/show"
  get "users/show"
  get "user/show"
  get "search/result"
  mount RedactorRails::Engine => '/redactor_rails'
  get "index/home"
  resources :posts
  
  get "/list/:id", to: 'userslist#show', as: :userlist_show

  resources :asks do
    resources :comments
  end

  resources :meetups

  resources :news
  
  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "errors/access_denied"
  get 'access_denied' => 'errors#access_denied', as: :access_denied
  

  root 'index#home'

end

app/models/ask.rb
class Ask
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :title, type: String
  field :content, type: String
  field :date, type: String
  field :complete, type: Boolean
    
  field :comment_id, type: String    
  field :user_id, type: String
  field :user_email, type: String
  field :user_full_name, type: String

 # embeds_many :comments
  has_many :comments, class_name: 'Comment', inverse_of: :ask 
  belongs_to :user, class_name: 'User', inverse_of: :asks
  
    def self.search(search)
        if search
           Ask.any_of({ title: /#{search}/ })
        else
           scoped
        end
    end
  
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  before_action :set_ask, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource param_method: :my_sanitizer

  # GET /asks
  # GET /asks.json
  def index
    @asks = Ask.all.order_by(created_at: :desc).page(params[:page]).per(4)
    @user = current_user
    @meetup = Meetup.last
    @news = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /asks/1
  # GET /asks/1.json
  def show
    @meetup = Meetup.last
    @news = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /asks/new
  def new
    @ask = Ask.new
    @meetup = Meetup.last
    @news = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /asks/1/edit
  def edit
  end

  # POST /asks
  # POST /asks.json
  def create

    @ask = current_user.asks.new(ask_params)
    @ask.user_email = current_user.email
    @ask.user_full_name = current_user.full_name

    respond_to do |format|
      if @ask.save
        format.html { redirect_to @ask, notice: 'Ask was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ask }
      else
        format.html { render action: 'new' }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asks/1
  # PATCH/PUT /asks/1.json
  def update
    respond_to do |format|
      if @ask.update(ask_params)
        format.html { redirect_to @ask, notice: 'Ask was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asks/1
  # DELETE /asks/1.json
  def destroy
    @ask.destroy
    respond_to do |format|
      format.html { redirect_to asks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ask
      @ask = Ask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ask_params
      params.require(:ask).permit(:title, :content, :user_email, :complete, :user_id)
    end

    def my_sanitizer
      params.require(:ask).permit(:name)
    end
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/views/asks/_form.html.erb
<%= form_for(@ask) do |f| %>
  <% if @ask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ask.errors.count, "error") %> prohibited this ask from being saved:</h2>

      <ul>
      <% @ask.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asks/_form.html.haml
.edit-block
  =form_for(@ask) do |f|
    =f.label :Запитання, :class => "edit-block-label"
    =f.text_field :title, :class => "title"
    =f.label :Опис, :class => "edit-block-label"
    =f.text_area :content, :class => "redactor"
    .buttons-block
      =f.submit :class => "more-button_blue", :style => "margin-top: 20px;"
    .clear-both

app/views/asks/edit.html.erb
<h1>Editing ask</h1>

<%= render 'form' %>

<%= link_to 'Show', @ask %> |
<%= link_to 'Back', asks_path %>

app/views/asks/index.html.erb
<% if @ask.size == 0 %>
    <%= @user.user_email %>
<% end %>
<h1>Listing asks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Email</th>
      <th>Answer</th>
      <th>Complete</th>
    </tr>
  </thead>

  <tbody>
    <% @asks.each do |ask| %>
      <tr>
        <td><%= ask.title %></td>
        <td><%= ask.content %></td>
        <td><%= ask.user_email %></td>
        <td><%= ask.comments.count %></td>
        <% if ask.complete == true %>
            <td><%=ask.complete.to_s %></td>
        <% else %>
            <td>false</td>
        <% end %>    
        <td><%= link_to 'Show', ask %></td>
        <% if current_user.id == ask.user_id || @user.has_role?(:admin) %>
            <td><%= link_to 'Edit', edit_ask_path(ask) %></td>
            <td><%= link_to 'Destroy', ask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ask', new_ask_path %>

app/views/asks/index.html.haml
.wrapper
  =render 'partial/header'
  =render 'asks/partial/content'
  =render 'partial/footer'
    

app/views/asks/new.html.erb
<h1>New ask</h1>

<%= render 'form' %>

<%= link_to 'Back', asks_path %>

app/views/asks/new.html.haml
.wrapper
  =render 'partial/header'
  =render 'asks/partial/newcontent'
  =render 'partial/footer'

app/views/asks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ask.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @ask.content %>
  <p><%= @ask.comments.count %></p>
</p>


<% if user_signed_in? %>
  <% if current_user.id == @ask.user_id %>
      <%= link_to 'Edit', edit_ask_path(@ask) %> |
      <%= link_to 'Back', asks_path %> |
      <%= form_for(@ask) do |f| %>
          <p><%= f.check_box :complete %></p>
          <%= f.submit %>
      <% end %>
  <% else %>
      <%= link_to 'Back', asks_path %>
  <% end %>

  <% if @ask.comments.size > 0 %>
    <h2>Comments</h2>
    <% for comment in @ask.comments %>
      <h3><%= comment.name %></h3>
      <h3><%= comment.user_email %></h3>
      <p><%= comment.content %></p>
    <% end %>
  <% end %>
  
  <h2>New Comment</h2>
  <%= form_for [@ask, Comment.new] do |f| %>
    <p><%= f.label :name %> <%= f.text_field :name %></p>
    <p><%= f.text_area :content, :rows => 10 %></p>
    <p><%= f.submit %></p>
  <% end %>
  <% else %>
  <%= link_to 'Back', asks_path %>
<% end %>

app/views/asks/show.html.haml
.wrapper
  =render 'partial/header'
  =render 'asks/partial/contentsingle'
  =render 'partial/footer'
    