config/routes.rb
Its30::Application.routes.draw do
  
  get "userslist/show"
  get "users/show"
  get "user/show"
  get "search/result"
  mount RedactorRails::Engine => '/redactor_rails'
  get "index/home"
  resources :posts
  
  get "/list/:id", to: 'userslist#show', as: :userlist_show

  resources :asks do
    resources :comments
  end

  resources :meetups

  resources :news
  
  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "errors/access_denied"
  get 'access_denied' => 'errors#access_denied', as: :access_denied
  

  root 'index#home'

end

app/models/meetup.rb
class Meetup
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :title, type: String
  field :content, type: String
  field :excerpt, type: String
  field :date, type: String
  field :address, type: String
  field :imagem, type: String
  
  mount_uploader :imagem, ImagemUploader
  
    def self.search(search)
        if search
           Meetup.any_of({ title: /#{search}/ })
        else
           scoped
        end
    end
  
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :set_meetup, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource param_method: :my_sanitizer

  # GET /meetups
  # GET /meetups.json
  def index
    @meetups = Meetup.all.order_by(created_at: :desc).page(params[:page]).per(3)
    @meetup = Meetup.last
    @news = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /meetups/1
  # GET /meetups/1.json
  def show
    @news = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /meetups/new
  def new
    @meetup = Meetup.new
     @news = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /meetups/1/edit
  def edit
    @news = News.all.order_by(created_at: :desc).limit(3)
  end

  # POST /meetups
  # POST /meetups.json
  def create
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meetup }
      else
        format.html { render action: 'new' }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetups/1
  # PATCH/PUT /meetups/1.json
  def update
    respond_to do |format|
      if @meetup.update(meetup_params)
        format.html { redirect_to @meetup, notice: 'Meetup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetups/1
  # DELETE /meetups/1.json
  def destroy
    @meetup.destroy
    respond_to do |format|
      format.html { redirect_to meetups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meetup
      @meetup = Meetup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meetup_params
      params.require(:meetup).permit(:title, :content, :excerpt, :date, :address, :imagem)
    end
    
    def my_sanitizer
      params.require(:post).permit(:name)
    end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/partial/_buttonsblock.html.haml
.buttons-block
  -if user_signed_in?
    - if current_user.has_role?(:admin)
      =link_to 'Редагувати', edit_meetup_path(@meetup), class: "more-button_blue"
      =link_to 'Видалити', @meetup, method: :delete, data: { confirm: 'Are you sure?' }, class: "more-button_blue"
      =link_to 'Назад', @meetup_index_path, class: "more-button_blue"
  -else
    =link_to 'Назад', @meetup_index_path, class: "more-button_blue"
.clear-both

app/views/meetups/partial/_content.html.haml
.content
  .row
    %h2.content-header Події
    =render 'meetups/partial/contentright'
    =render 'partial/sidebar/left/sidebar' 
    

app/views/meetups/partial/_contentright.html.haml
.large-8.medium-8.large-push-4.medium-push-4.small-12.columns
  .content-right
    .content-right_news.padding-lr-15
      =render 'meetups/partial/eventsblock'
      =paginate @meetups

app/views/meetups/partial/_contentsingle.html.haml
.content
  .row
    %h2.content-header Події
    =render 'meetups/partial/singleevent'
    =render 'partial/sidebar/left/sidebar' 
    

app/views/meetups/partial/_eventsblock.html.haml

- @meetups.each do |b|
  .content-right_news_inner
    .large-12.medium-12.small-12.columns
      .large-3.medium-3.small-4.columns
        .content-right_news_inner_post-img
          =link_to b do
            =image_tag b.imagem_url() if b.imagem? 
      .large-9.medium-9.small-8.columns
        .content-right_news_inner_post-header
          %h5=b.title
      .large-9.medium-9.small-8.columns.content-right_news_inner_post-text-button_blue-author-time-fix
        .content-right_news_inner_post-text
          .cut
            %p=simple_format(b.content)
        .clear-both
        .content-right_news_inner_post-author-time
          %p=b.created_at.to_s(:db)
        =link_to 'Детальніше', b, :class => "more-button_blue"
    .clear-both
-if user_signed_in?
  -if current_user.has_role?(:admin)
    =link_to 'Додати подію', new_meetup_path, :class => "more-button_blue"

app/views/meetups/partial/_singleevent.html.haml
.large-8.medium-8.large-push-4.medium-push-4.small-12.columns
  .content-right
    .single-post.padding-lr-15
      = image_tag @meetup.imagem_url() if @meetup.imagem?
      %h2=@meetup.title
      .single-post_author-time
        %p=@meetup.date
        %p=@meetup.address
      %p.single-post_text=simple_format(@meetup.content)
    =render 'meetups/partial/buttonsblock'
                 