config/routes.rb
Its30::Application.routes.draw do
  
  get "userslist/show"
  get "users/show"
  get "user/show"
  get "search/result"
  mount RedactorRails::Engine => '/redactor_rails'
  get "index/home"
  resources :posts
  
  get "/list/:id", to: 'userslist#show', as: :userlist_show

  resources :asks do
    resources :comments
  end

  resources :meetups

  resources :news
  
  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "errors/access_denied"
  get 'access_denied' => 'errors#access_denied', as: :access_denied
  

  root 'index#home'

end

app/models/news.rb
class News
  include Mongoid::Document
  include Mongoid::Timestamps

  resourcify

  field :title, type: String
  field :content, type: String
  field :user_id, type: String
  field :user_email, type: String
  field :imagen, type: String
  
  mount_uploader :imagen, ImagenUploader

  belongs_to :user, class_name: 'User', inverse_of: :news
  
    def self.search(search)
        if search
           News.any_of({ title: /#{search}/ })
        else
           scoped
      end
    end
  
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user! , only: [:edit, :update, :destroy]
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource param_method: :my_sanitizer


  # GET /news
  # GET /news.json
  def index
    @news = News.all.order_by(created_at: :desc).page(params[:page]).per(3)
    @news_other = News.all.order_by(created_at: :desc).limit(5)
    @posts = Post.all
    @meetup = Meetup.last

    @user = current_user

    if @user.nil?
      @user = User.new
    else
      @user = current_user
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @user = current_user
    @meetup = Meetup.last
    @news_all = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /news/new
  def new
    @news = News.new
    @meetup = Meetup.last
    @news_all = News.all.order_by(created_at: :desc).limit(3)
  end

  # GET /news/1/edit
  def edit
    @meetup = Meetup.last
    @news = News.all.order_by(created_at: :desc).page(params[:page]).per(3)
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content, :imagen)
    end

    def my_sanitizer
      params.require(:news).permit(:name)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/partial/_anothernews.html.haml
.content-left_another-news
  %h5 Інші новини:
  -@news_all.each do |n|
    .content-left_another-news-block
      .content-left_another-news_time=n.created_at.to_s(:db)
      .content-left_another-news_text
        =link_to n do
          =n.title
.clear-block

app/views/news/partial/_buttonsblock.html.haml
.buttons-block
  - if current_user.has_role?(:admin)
    //=link_to 'Редагувати', edit_news_path(@news), class: "more-button_blue"
    =link_to 'Видалити', @news, method: :delete, data: { confirm: 'Are you sure?' }, class: "more-button_blue"
    =link_to 'Назад', news_index_path, class: "more-button_blue"
  - else
    =link_to 'Назад', news_index_path, class: "more-button_blue"
.clear-both

app/views/news/partial/_content.html.haml
.content
  .row
    %h2.content-header Новини
    =render 'news/partial/contentright'
    =render 'partial/sidebar/left/sidebar' 
    

app/views/news/partial/_contentright.html.haml
.large-8.medium-8.large-push-4.medium-push-4.small-12.columns
  .content-right
    .content-right_news.padding-lr-15
      =render 'news/partial/newsblock' 

app/views/news/partial/_contentsingle.html.haml
.content
  .row
    %h2.content-header Новини
    =render 'news/partial/singlenews'
    =render 'news/partial/sidebar' 
    

app/views/news/partial/_editcontent.html.haml
.content
  .row
    %h2.content-header Редагування новини
    =render 'news/partial/editcontentright'
    =render 'partial/sidebar/left/sidebar' 

app/views/news/partial/_editcontentright.html.haml
.large-8.medium-8.large-push-4.medium-push-4.small-12.columns
  .content-right
    .single-post.padding-lr-15
      =render 'form'
      .buttons-block
        =link_to 'Back', posts_path, class: "more-button_blue"
        =link_to 'Show', @news, class: "more-button_blue"
      .clear-both

app/views/news/partial/_newcontent.html.haml
.content
  .row
    %h2.content-header Створити новину
    =render 'news/partial/newcontentright'
    =render 'news/partial/sidebar' 

app/views/news/partial/_newcontentright.html.haml
.large-8.medium-8.large-push-4.medium-push-4.small-12.columns
  .content-right
    .single-post.padding-lr-15
      =render 'newform'
      .buttons-block
        =link_to 'Назад', news_index_path, class: "more-button_blue"
        =link_to 'Показати', @news, class: "more-button_blue"
      .clear-both

app/views/news/partial/_newsblock.html.haml
-if user_signed_in?
  -if current_user.has_role?(:admin)
    =link_to 'Додати новину', new_news_path, :class => "more-button_blue"
- @news.each do |b|
  .content-right_news_inner
    .large-12.medium-12.small-12.columns
      .large-3.medium-3.small-4.columns
        .content-right_news_inner_post-img
        = image_tag 'https://its-c9-verkalets.c9.io/uploads/user/userspro/5344328265782d7b82000000/gravater.png'
      .large-9.medium-9.small-8.columns
        .content-right_news_inner_post-header
          %h5=b.title
      .large-9.medium-9.small-8.columns.content-right_news_inner_post-text-button_blue-author-time-fix
        .content-right_news_inner_post-text
          .cut
            %p=simple_format(b.content)
        .clear-both
        .content-right_news_inner_post-author-time
          %p=b.created_at.to_s(:db)
        =link_to 'Детальніше', b, :class => "more-button_blue"
.clear-both
  = paginate @news


app/views/news/partial/_postsblock.html.haml
- @posts.each do |b|
  .content-right_news_inner
    .large-12.medium-12.small-12.columns
      .large-3.medium-3.small-4.columns
        .content-right_news_inner_post-img
      .large-9.medium-9.small-8.columns
        .content-right_news_inner_post-header
          %h5=b.title
          =image_tag b.imagep_url() if b.imagep?
      .large-9.medium-9.small-8.columns.content-right_news_inner_post-text-button_blue-author-time-fix
        .content-right_news_inner_post-text
          %p=simple_format(b.content)
        .clear-both
        .content-right_news_inner_post-author-time
          %p=b.created_at.to_formatted_s(:short) + 'часов назад'
        =link_to 'Детальніше', b, :class => "more-button_blue"
.clear-bothа

app/views/news/partial/_sidebar.html.haml
.large-4.medium-4.small-12.large-pull-8.medium-pull-8.columns
  .content-left
    =render 'partial/sidebar/left/nextevent'
    =render 'partial/sidebar/left/company'
    =render 'news/partial/anothernews'

app/views/news/partial/_singlenews.html.haml
.large-8.medium-8.large-push-4.medium-push-4.small-12.columns
  .content-right
    .single-post.padding-lr-15
      = image_tag 'https://its-c9-verkalets.c9.io/uploads/user/userspro/5344328265782d7b82000000/gravater.png'
      %h2=@news.title
      .single-post_author-time
        %p=@news.created_at.to_s(:db)
      .single-post_text
        %p=simple_format(@news.content)
    =render 'news/partial/buttonsblock'
                 